### ISSUE TITLE
V12 foundry Item Qualities are broken

### ISSUE THREAD

**Issue by Roxas21** [Mezryss/FVTT-Genesys#178]
trying the new update Genesys 0.2.11 for V12 Foundry, and any attacks that have an item quality give the following error message and does not roll the attack, is this something with my version or a new bug? is Asking since i recently updated from V10 of Foundry. 
![billede](https://github.com/user-attachments/assets/06b8f43c-586d-4527-a3b9-4faeb947ed03)

**Comment by Assembling-Kings** [comment]
Which version of the system were you using before the update? I ran a game today and people were using their attacks without any problem. Could you post any errors on the console log (hit F12 on your browser or the desktop app when that error happens and post the message displayed there).

If possible try to re-create the item, add qualities, and check if that behaves as expected. If so then the problem might be the data on your current items.

**Comment by Roxas21** [comment]
Sure, 
I was using Foundry V10.351 and Genesys 0.2.10
This is the error I get when hitting f12 after making a roll
![billede](https://github.com/user-attachments/assets/7070a844-7cb8-48ec-86c4-936a9212e631)
it seems that the error only arrives if I have symbols in the description of the Item quality. Even if I rewrite the text it still breaks.
I did try and make a new item which is where I learned this. just giving the log for that one too.
![billede](https://github.com/user-attachments/assets/1c6588fe-298b-42fd-b96e-d0fd4045ffb4)

**Comment by Assembling-Kings** [comment]
Yeah, I'm not sure what might be happening since I've tested it again and it works fine. How did you upgrade FVTT? For mayor version updates you're supposed to uninstall the old version and install the new one, otherwise weird stuff might happen. You can also try uninstalling the system and reinstalling it again. Sometimes this can fix problems with bad updates. If none of that works let me know.
