### ISSUE TITLE
Passive Effects in Dice Pool

### ISSUE THREAD

**Issue by Arctanis** [Mezryss/FVTT-Genesys#195]
It seems that Passive Effects only affect the dice pool UI when the base talent/quality/item is edited. No changes in the character sheet will apply to the dice pool. It's only a quality of life issue, but it would be nice to just modify existing character sheets rather than change the base item, reimport it to the sheets, and then do that again (or clutter up the items tab with multiple ranks of things like Adversary).

**Comment by Assembling-Kings** [comment]
Your explanation confuses me a little so let me explain how the effects currently work.

Currently effects are copied from a dropped item into the character sheet. So any effect on an item after it's dropped is an independent copy from the one copied on the sheet. You need to edit the effect on the sheet directly in order to see changes.

**Comment by Arctanis** [comment]
Sorry, it was late when I wrote it originally.

The issue is that when I edit Talent/Abilities/Gear in a character's sheet locally, they don't actually apply the passive effect to the dice pool. There's no option to check it and add it to the pool. 
Example: I made a monster weeks prior, and it has the Adversary talent. I edit the talent in the monster's prototype sheet so that when it is targeted by a player it will provide the option to upgrade the checks against it. The problem is that it doesn't do that. I have to edit the original talent, and reimport that talent into the character sheet for it to register. Local edits don't work.

**Comment by Assembling-Kings** [comment]
Edits on the actor sheet should work like I mentioned. Here is an example of me doing it:
1. Here's a "Character" with no items on its inventory an a "Gear" item I created with one effect (one boost dice in _Computers_ checks).
![image](https://github.com/user-attachments/assets/1c5093c9-d470-4bed-ac56-1db8f7b7a6e4)
2. I dropped the "Gear" on the "Character" sheet as seen below.
![image](https://github.com/user-attachments/assets/3cf87070-c803-41e3-abf3-7e2cd9979aba)
3. You can see that the effect was copied into the "Character" and that when I try to roll _Computers_ it shows the Boost dice.
![image](https://github.com/user-attachments/assets/e924a2b3-e7c0-4bdd-8a76-449197c7f18d)
4. I then go into the copied effect and edit it to instead add 2 Boost dice and when I try to roll I see the changes.
![image](https://github.com/user-attachments/assets/66ba76c9-1a15-4e2c-9937-d01b85b924ad)

So you need to edit the effect on the "Character" sheet and not on the item sheet because like I mentioned they are independent after the item is dropped and its effects copied.
