### ISSUE TITLE
In ForgeVtt Genesys fonts dont load

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#23]
In forgeVtt V10, the console shows the following error:

foundry.js:63200 Font family "Genesys Symbols" failed to load:  DOMException: A network error occurred

**Comment by Mezryss** [comment]
Hmm.. I suspect that this might be a Forge VTT issue rather than a system one, but if the other fonts are loading that might not be the case after all.

Were any other fonts failing to load in the console, or only this one?

It's not Forge VTT, but I'm going to see if I can reproduce the issue in my headless server (as opposed to my dev env)..

**Comment by Lyinggod** [comment]
Expanded image of error
![image](https://user-images.githubusercontent.com/16379736/222930460-840857d3-746c-4430-8a89-19349fcfa667.png)

**Comment by Mezryss** [comment]
From discussion in Discord, it looks like this resolved itself when updating to 0.1.1 - I suspect ForgeVTT just had an issue with extracting the zip file before.
