### ISSUE TITLE
Nothing in the world

### ISSUE THREAD

**Issue by kHabicht** [Mezryss/FVTT-Genesys#38]
Sorry to ask but I think I'm missing something. No expert on Fundry, but I am fairly used to the program.

Instaled via foundry (a couple of times just to be sure), created a new world to try out but nothing's there but a skill compendium. I most likley doing something wrong or missing something vital to do!? 

Workflow (realy short):
Creating a new actor and looking for careers, talents and other things to drag and drop gives me nothing. There is absolutley nothing to drag in. The only thing I can find is the skills compendium and that contains only the names of the skills (opening one gives me no text).

I have tried looking in the star wars ffg channel on discord but found nothing. For the record, I'm no fan of discords search function and the channel is quite crowded with multiple questions of various kind. I mainly use Discord for ingame voice and chat.

Sorry if I missed something here but I'we looked around and found nothing to help me.

Using 0.1.6

**Comment by Mezryss** [comment]
This is intentional. The content for Genesys isn't under an open license; I can't include information on talents, careers, etc.

For now, you have to manually enter the data. As a future piece of work I intend to add support for data imports from various sources, but I will not be including anything other than skills (and even then, only their names & associated Characteristics) directly in the system data.
